# Generated by Django 5.0.6 on 2024-07-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('type', models.CharField(default='default', max_length=10, primary_key=True, serialize=False)),
                ('win', models.IntegerField()),
                ('lose', models.IntegerField()),
            ],
        ),
    ]
