# Generated by Django 5.0.6 on 2024-07-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicebe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='type',
        ),
        migrations.AddField(
            model_name='stat',
            name='nick',
            field=models.CharField(default='nick', max_length=30, primary_key=True, serialize=False),
        ),
    ]
