# Generated by Django 5.0.6 on 2024-07-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicebe', '0002_remove_stat_type_stat_nick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='lose',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='win',
        ),
        migrations.AddField(
            model_name='stat',
            name='even_lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='even_win',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='odd_lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='odd_win',
            field=models.IntegerField(default=0),
        ),
    ]
