version: "2"

services:
  mariadb:
    image: mariadb:junhylee
    init: true
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb-volume:/var/lib/mysql
    build: ./requirements/mariadb
    networks:
      inception:
    expose:
      - "3306"
    tty: true
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mariadb-admin ping -h localhost -u root --password=$$MARIADB_ROOT_PASSWORD || exit 1",
        ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 1s
    restart: on-failure:3

  wordpress:
    init: true
    image: wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - wordpress-volume:/var/www
    build: ./requirements/wordpress
    expose:
      - "9000"
    healthcheck:
      test: ["CMD-SHELL", "cgi-fcgi -bind -connect localhost:9000 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 1s
    restart: on-failure:3
    networks:
      - inception

  nginx:
    init: true
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - wordpress-volume:/var/www
    build: ./requirements/nginx
    expose:
      - "443"
    ports:
      - "443:443"
    healthcheck:
      test: ["CMD-SHELL", "curl -k https://localhost:443 || exit 1"]
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 1s
    restart: on-failure:3
    networks:
      - inception
    tty: true

volumes:
  mariadb-volume:
    name: mariadb-volume
    # 볼륨 저장공간
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DIR}/mariadb
      o: bind

  wordpress-volume:
    name: wordpress-volume
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DIR}/wordpress
      o: bind

networks:
  inception:
    driver: bridge
    name: inception