# Generated by Django 5.0.6 on 2024-07-01 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('nick', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.user')),
                ('is_fourty', models.BooleanField(default=False)),
                ('is_email', models.BooleanField(default=False)),
            ],
        ),
    ]
