# Generated by Django 5.0.6 on 2024-07-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email_code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
